#!/bin/bash

#Enable email notificaitons when job begins and ends, uncomment if you need it
#SBATCH --mail-user=cwchanbh@connect.ust.hk #Update your email address
##SBATCH --mail-type=begin
#SBATCH --mail-type=end

#SBATCH --job-name=a1
#SBATCH --output=slurm-%A_%x.out
#SBATCH --error=slurm-%A_%x.err
#SBATCH --partition=cpu
#SBATCH -N 1 -n 40
#SBATCH --exclusive


export JULIA_NUM_THREADS=40
export JULIA_DEPOT_PATH="~/.julia/packages/"
#$HOME/julia-1.9.2/bin/julia   "script/single.jl"
#$HOME/julia-1.9.2/bin/julia   "script/single3D.jl"
#$HOME/julia-1.9.2/bin/julia   "script/submit/Pe80a5.jl"
#$HOME/julia-1.9.2/bin/julia	-t 40 script/single3D.jl 20 -3
#$HOME/julia-1.9.2/bin/julia	-t 40 script/mutiple3Dlinear.jl -3

#$HOME/julia-1.9.2/bin/julia	-t 40 script/mutiple3D.jl -3

#$HOME/julia-1.9.2/bin/julia	-t 40 script/single3D.jl  -3
$HOME/julia-1.9.2/bin/julia	-t 40 script/single3D.jl 10 -1
$HOME/julia-1.9.2/bin/julia	-t 40 script/single3D.jl 20 -1
$HOME/julia-1.9.2/bin/julia	-t 40 script/single3D.jl 30 -1
$HOME/julia-1.9.2/bin/julia	-t 40 script/single3D.jl 40 -1
$HOME/julia-1.9.2/bin/julia	-t 40 script/single3D.jl 50 -1
$HOME/julia-1.9.2/bin/julia	-t 40 script/single3D.jl 60 -1
#$HOME/julia-1.9.2/bin/julia	-t 40 script/single3D.jl 90 -1
#$HOME/julia-1.9.2/bin/julia	-t 40 script/single3D.jl 100 -1


